### ISSUE TITLE
Cleanup GangaRelease/tools

### ISSUE THREAD

**Issue by egede** [ganga-devs/ganga#2114]
The directory [GangaRelease/tools](https://github.com/ganga-devs/ganga/tree/develop/ganga/GangaRelease/tools) is full of files that are no longer used. It should be identified which files (if any) we still use and the rest deleted.

**Comment by egede** [comment]
@mesmith75 Anything that we still use in this directory?

**Comment by mesmith75** [comment]
We still use [check-new-ganga.py](https://github.com/ganga-devs/ganga/blob/develop/ganga/GangaRelease/tools/check-new-ganga.py) , [ganga-cvmfs-install-dev.sh](https://github.com/ganga-devs/ganga/blob/develop/ganga/GangaRelease/tools/ganga-cvmfs-install-dev.sh), [ganga-cvmfs-install.sh](https://github.com/ganga-devs/ganga/blob/develop/ganga/GangaRelease/tools/ganga-cvmfs-install.sh). The rest can go

**Comment by shalearkane** [comment]
We have this line in `index.rst`, https://github.com/ganga-devs/ganga/blob/2dbc3bb9f862261f998a68342e93d02dc9a1ef8a/doc/sysadmin/index.rst?plain=1#L9-L10
Removing `ganga-install` should also reflect the changes in the document. Also in https://github.com/ganga-devs/ganga/blob/2dbc3bb9f862261f998a68342e93d02dc9a1ef8a/ganga/GangaND280/doc/installGanga.dox#L16 we have a reference to the tool.

Finally, I looked if the tools are referenced anywhere else,
We have some inter-dependencies within the tools:
```yaml
ganga-git-release:
    - ganga-git-create-pre
        - ganga-install-externals
    - ganga-git-create-final
        - ganga-install-externals
    - ganga-git-set-version
    - ganga-git-start-release
    - ganga-release-html
    - predist
    - acl

rpm_builder:
    - postun-packages.sh
 
retro_schema-gen:
    - schema_gen
```
So I am cleaning up the whole directory except [check-new-ganga.py](https://github.com/ganga-devs/ganga/blob/develop/ganga/GangaRelease/tools/check-new-ganga.py) , [ganga-cvmfs-install-dev.sh](https://github.com/ganga-devs/ganga/blob/develop/ganga/GangaRelease/tools/ganga-cvmfs-install-dev.sh), [ganga-cvmfs-install.sh](https://github.com/ganga-devs/ganga/blob/develop/ganga/GangaRelease/tools/ganga-cvmfs-install.sh).
